### ISSUE TITLE
dark mode feature  enable/ disable 

### ISSUE THREAD

**Issue by EcomGraduates** [EcomGraduates/eg-theme-snippets#18]
choose the overall color scheme of the store from a few presets. Kind of like a dark mode toggle but one where you can pick between a few color schemes instead of just light / dark.

**Comment by EcomGraduatesDev** [comment]
This is sth that can not implemented on different theme, but rather needs to be target with a specific theme, plus it require an tremendous amount of work and lots of files to be edited/changed.
