### ISSUE TITLE
Coundown timer

### ISSUE THREAD

**Issue by EcomGraduates** [EcomGraduates/eg-theme-snippets#20]

**Comment by EcomGraduates** [comment]
![image](https://user-images.githubusercontent.com/74157486/143911183-7dbc7880-3822-47a5-87a0-f66f19c2e0ac.png)
 what is this image? 
![image](https://user-images.githubusercontent.com/74157486/143911221-381141f4-a12c-4f6d-84b3-739dcfe8d81c.png)

**Comment by EcomGraduatesDev** [comment]
That's an embed code by Powr. It is just to showcase what you can do with the HTML section. 
https://www.powr.io/plugins/countdown-timer/standalone?id=30707437&

**Comment by EcomGraduates** [comment]
this  is a html   
would love if can to be a section   with settings    and not through power io
