### ISSUE TITLE
Stories

### ISSUE THREAD

**Issue by EcomGraduates** [EcomGraduates/eg-theme-snippets#24]
stories  feature with mp4  time limits  like swaggin momma  

![image](https://user-images.githubusercontent.com/74157486/143784912-fc7725ae-bce5-4d20-bd08-f953d2a6aeb0.png)

**Comment by EcomGraduatesDev** [comment]
Adding a lightbox to this feature will complicate the section unnecessarily. Normally, these stories should be linked to their respective collections like on HeavenlyWoke (New, Best-Selling, etc), plus we have to have a license for that lightbox to put in. Let this be in this way for the moment, and if users asks for it we can implement it later.

**Comment by EcomGraduates** [comment]
looks really nice!
https://video.ecomgraduates.com/JrunYXrO

**Comment by EcomGraduatesDev** [comment]
done the stories with the lightgalleryJS but we need to release the snippet as Free
