### ISSUE TITLE
bug with  faq - color settings  

### ISSUE THREAD

**Issue by EcomGraduates** [EcomGraduates/eg-theme-snippets#36]
when changing the backgroudn colors, it doesnt show  the text  

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/74157486/154468230-89657c55-fab3-46e3-a79e-9b7a8dea4df8.png">

i have the color issue too  on the theme  in the fq section 
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/74157486/154468525-9bbd8727-24e4-48fb-b02c-1cd5943ef039.png">
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/74157486/154470257-aa68d9c5-0f81-4e5a-ab91-0d2516c841e1.png">

**Comment by EcomGraduatesDev** [comment]
Should be fine now
