### ISSUE TITLE
EG Spinning Wheel - section

### ISSUE THREAD

**Issue by EcomGraduatesDev** [EcomGraduates/eg-theme-snippets#48]
https://codepen.io/tonyfelice/pen/Bzjamz
https://codepen.io/GhostCode99/pen/BaQePwW
http://jsfiddle.net/neerajsinghsonu/g4yt9u6k/

**Comment by EcomGraduatesDev** [comment]
Almost done, it needs a bit more work but I think I got the difficult parts done. It took more time than I thought but still, I think it is a good snippet to have. I will check BigsStore issues today as well.

**Comment by EcomGraduates** [comment]
thank you so much  it looks great!  
glen will  be  making that vid  

thank you

**Comment by EcomGraduatesDev** [comment]
no rush yet, it still needs some work to be finished

**Comment by EcomGraduatesDev** [comment]
Ok finally done. Please test it on your own and let me know. No need to be perfect though, we can update it again in the future, but so far I think it's working very well. Also, I have created a section on the homepage to advertise this section. Also, I think that is better that we have a conversation before you make the video so that I can explain a thing or two if necessary.

**Comment by EcomGraduates** [comment]
waht are the changes ?   needed for the  section
