### ISSUE TITLE
cart drawer bug- does not update when added 

### ISSUE THREAD

**Issue by EcomGraduates** [EcomGraduates/eg-theme-snippets#50]
here is a exmamle of someone having the issue 
https://www.awesomescreenshot.com/video/8179644?key=42878e8e381385776e8132d373fcd24b

**Comment by EcomGraduatesDev** [comment]
Get admin access, i think the client has not copied the codes correctly.

**Comment by EcomGraduatesDev** [comment]
Do not close this yet, it is fixed on the client, but I will see to inspect this a bit more, to find a better approach.

**Comment by EcomGraduatesDev** [comment]
Should be done this change for step 3

Step 3:
Open file `assets/cart-notification.js` and change the following code: (around line 34)

Find the following code:
```
renderContents(parsedState) {
    this.productId = parsedState.id;
    this.getSectionsToRender().forEach((section => {
      document.getElementById(section.id).innerHTML =
        this.getSectionInnerHTML(parsedState.sections[section.id], section.selector);
    }));

    if (this.header) this.header.reveal();
    this.open();
}
```

Replace it with:
```
 renderContents(parsedState) {
   loadEgCartDrawer(true);
}
```
