### ISSUE TITLE
Dawn - Quick View

### ISSUE THREAD

**Issue by EcomGraduatesDev** [EcomGraduates/eg-theme-snippets#54]

**Comment by EcomGraduatesDev** [comment]
Made some good progress with it, still has more work

**Comment by EcomGraduatesDev** [comment]
Made more progress, still, need needs work. We have to obey the Dawn theme logic and try to use as many elements from it as possible. I have a good idea for it as well, hopefully, I will be able to implement it.

**Comment by EcomGraduatesDev** [comment]
So I manage to implement the prev/next buttons which can move from one product to the other on the same product list.
This feature is really good to have and usefull as well. It was quite tricky to archive it, but I'm satisfied with the results, and as far as I know, no one else has done this before.

**Comment by EcomGraduatesDev** [comment]
Made further progress with this snippet, now it is left in the ATC area along with the product options.

**Comment by EcomGraduatesDev** [comment]
To do
- [ ] Show buttons after filters are set on collection pages
- [ ] Refactor pricing area
- [ ] Ajax ATC form
- [ ] Wishlist button
- [ ] Mobile view

**Comment by EcomGraduatesDev** [comment]
Ok, finally finished. Very few changes needed

1- Add the section file `sections/eg-quick-view-modal.liquid`

2- Open file `layout/theme.liquid`

Find (near the bottom of the file):
`{% section 'footer' %}`

Add after:
`{% section 'eg-quick-view-modal' %}`

3- Open file: `snippets/card-product.liquid`

Find (near the top of the file):
`<div class="card-wrapper underline-links-hover">`

Replace it with:
`<div class="card-wrapper underline-links-hover" data-product-handle="{{ card_product.handle }}">`

**Comment by EcomGraduatesDev** [comment]
- Note, currently, the form selector works with variants and not product options, the logic is way too much to put there, especially considering that it needs to work with Dawn logic and to be all within a file. But I think it makes sense with variant selectors because the Quick view mode is meant to be simple and just a preview. But still, we can work on this in the future.

- Again we can enhance this snippet in the future if needed with other options like quantity, our Wishlist buttons, etc. But at this stage i think the foundation is very good and ready for release.

**Comment by EcomGraduates** [comment]
i added it in the 4.0 dawn to test it out  
didnt seem to work  yet 

![image](https://user-images.githubusercontent.com/74157486/163891885-2d018337-318c-4d66-bcca-3b72739f319b.png)

**Comment by EcomGraduatesDev** [comment]
Ok fixed a small bug, it works fine now.
