### ISSUE TITLE
image-banner.liquid section - Allow images to be clickable with URL settings

### ISSUE THREAD

**Issue by EcomGraduates** [EcomGraduates/eg-theme-snippets#65]
![image](https://user-images.githubusercontent.com/74157486/163067402-898eff26-2609-4634-8136-3ad571c52c8c.png)

**Comment by EcomGraduatesDev** [comment]
This is just a small change, which we can't sell.

**Comment by EcomGraduates** [comment]
can you tell me the change and i can create a video for it 
some people were asking for it now

**Comment by EcomGraduatesDev** [comment]
**Note: You can not have text or buttons on the image/images but just 1 or 2 images mode that this section has**

Replace this file: `sections/image-banner.liquid` with the one in this repo
https://github.com/EcomGraduates/eg-theme-snippets/blob/main/sections/image-banner.liquid

- You will see now 2 other settings that you can enter the URL for each image
![Screen Shot 2022-04-18 at 10 25 20 AM](https://user-images.githubusercontent.com/90354202/163780155-3ac04d5b-c74b-4506-b4cd-7d5e792f578c.png)
