### ISSUE TITLE
customer - heavy dawn theme  - need slide out cart to work 

### ISSUE THREAD

**Issue by EcomGraduates** [EcomGraduates/eg-theme-snippets#66]
check  a customes dawn theme.  i  did the code correctly for the slide out cart but they have heavy  coded dawn
beauty-by-earth-natural-beauty.myshopify.com/

![image](https://user-images.githubusercontent.com/74157486/163269213-29cee5ad-692b-435c-817f-e09a4748d42d.png)

**Comment by EcomGraduatesDev** [comment]
Ok this should be solved, let me know if the customer is satisfied with this.
