### ISSUE TITLE
Scrollbar visible on windows - Quick View snippet

### ISSUE THREAD

**Issue by EcomGraduates** [EcomGraduates/eg-theme-snippets#67]
![image](https://user-images.githubusercontent.com/74157486/163281102-cd683f62-c304-429c-993a-539aadd889a2.png)

**Comment by EcomGraduatesDev** [comment]
I think the issue is only on Windows. Anyway I did a fix, let me know if its fine now.

**Comment by EcomGraduates** [comment]
thank you

my question is 
do they have the option to remove quick view and then it just becomes a atc btn again
