### ISSUE TITLE
Have option to have add to cart btn - Quick View snippet

### ISSUE THREAD

**Issue by EcomGraduatesDev** [EcomGraduates/eg-theme-snippets#68]
The quick view has already the option, do you mean something else?

![Screen Shot 2022-04-14 at 10 09 19 AM](https://user-images.githubusercontent.com/90354202/163342432-b7799195-eccb-4faf-81d5-51fb9b3c6b50.png)

**Comment by EcomGraduates** [comment]
thank you

my question is
do they have the option to remove quick view and then it just becomes a atc btn again

**Comment by EcomGraduatesDev** [comment]
The quick view snippet we are building does not interfere with the store's ATC, it simply adds a button for each product list item and then when clicked shows the modal as in the screenshot. All of this is built dynamically via JavaScript, which makes the whole snippet very fast and responsive.
