### ISSUE TITLE
dawn currency  converter?  

### ISSUE THREAD

**Issue by EcomGraduates** [EcomGraduates/eg-theme-snippets#69]
![image](https://user-images.githubusercontent.com/74157486/163468806-7accd7b7-8c26-42df-90d3-8faa86ac3453.png)

if its possbile

**Comment by EcomGraduatesDev** [comment]
Dawn theme for sure has already a currency converter feature and an official app to automatically find the currency, but it seems to have bad ratings, maybe we can do a snippet for it.

https://apps.shopify.com/geolocation

![Screen Shot 2022-04-16 at 9 31 30 AM](https://user-images.githubusercontent.com/90354202/163666183-ad168d3f-c6a8-4447-ad09-79f7f140b682.png)

**Comment by EcomGraduates** [comment]
might be good then - up to  you
