### ISSUE TITLE
customer - store bug 

### ISSUE THREAD

**Issue by EcomGraduates** [EcomGraduates/eg-theme-snippets#80]
you have  access to the theme 

https://santoshandmunu.myshopify.com/admin/themes

- [x] dawn cart and dawer not able to click out and leaves grey and not able to scroll -
- [x] the megamenu on the mobile,  leaves a btn mark  on the offcanvas 

<img width="585" alt="image" src="https://user-images.githubusercontent.com/74157486/165298677-1724bcfb-2ef4-4da9-bfc2-ac50a9b439e8.png">
<img width="585" alt="image" src="https://user-images.githubusercontent.com/74157486/165298708-7de43a1d-94bb-4739-b5c5-7c27351b5b1b.png">
<img width="585" alt="image" src="https://user-images.githubusercontent.com/74157486/165298733-49677b74-3b5c-4de7-9f0b-77cabfa5a5c8.png">

https://video.ecomgraduates.com/nOuR4YPR

**Comment by EcomGraduatesDev** [comment]
I have to check the other issue in megamenu, for me, it doesn't show that button are you mentioning. It seems they have added their own changes there.

**Comment by EcomGraduatesDev** [comment]
... also meanwhile, let me know if they are trying to work with codes on that or not so that i can erase all what's wrong there.

**Comment by EcomGraduates** [comment]
you can remove the  ones that are  making  the bugs please

**Comment by EcomGraduatesDev** [comment]
Fixed what the client was trying to archive.
